name: voucher_enquire
description: A new Flutter project.
repository: https://github.com/openimis/voucher_enquire_flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  graphql_flutter: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  generate: true
  uses-material-design: true

  assets:
    # To add files located in subdirectories, create an entry per directory.
    # Resolution-aware asset image variants are the only exception.
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
