name: Build App APK

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Flutter Doctor
        run: flutter doctor -v

      # Checkout the repository code and get packages.
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Dependencies
        run: |
          cd voucher_enquire
          flutter pub get

      - name: Build APK
        run: |
          cd voucher_enquire
          flutter build apk --split-per-abi --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: openimis-voucher-enquire-${{github.run_number}}-${{github.sha}}
          path: voucher_enquire/build/app/outputs/apk/*.apk